### PR TITLE
Add inline Twitter Bootstrap

### PR DESCRIPTION
**Pull request by DaAwesomeP**
<style[^>]*>.*Bootstrap v.* Copyright .* Twitter, Inc\.\* Licensed under.*<\/style>

### CODE REVIEW

**Comment by ElbertF** [comment]
Thanks!

**Comment by AliasIO** [comment]
I'd like to refine this pattern to not have `.*` in it. I'm removing it in the meantime. Do you have an example website that uses inline Bootstrap?

**Comment by DaAwesomeP** [comment]
http://derbyjs.com/

**Comment by AliasIO** [comment]
Great, thanks. I added it back in.

**Pull request merged**
